### ISSUE TITLE
Support async processing

### ISSUE THREAD

**Issue by wooorm** [mdx-js/eslint-mdx#203]
### Subject of the issue

`eslint-mdx` uses .processSync instead of .process, causing async plugins to fail.

```
Error: `processSync` finished async. Use `process` instead
Occurred while linting /Users/tilde/Code/oss/mdx/packages/remark-mdx/readme.md:1
    at assertDone (/Users/tilde/Code/oss/mdx/node_modules/unified/index.js:469:11)
    at Function.processSync (/Users/tilde/Code/oss/mdx/node_modules/unified/index.js:401:5)
    at Program (/Users/tilde/Code/oss/mdx/node_modules/eslint-plugin-mdx/lib/cjs.js:361:44)
    at /Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/tilde/Code/oss/mdx/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
```

### Your environment

*   **OS**: osx latest
*   **Packages**: 
*   **Env**: node 13.10, 6.14, yarn 1.22

### Steps to reproduce

`yarn format` in `mdx-js/mdx` (with changes on a branch)

### Expected behaviour

Support async plugins: https://github.com/mdx-js/eslint-mdx/blob/96fc83affd7f63d52d6b7fce6c15816e9a034a6b/packages/eslint-plugin-mdx/src/rules/remark.ts#L40

### Actual behaviour

Crash.

---

P.S. aside: you may be interested in [vfile-to-eslint](https://github.com/vfile/vfile-to-eslint)

**Comment by JounQin** [comment]
Yes, it is a known issue, and that's why [validate-links](https://github.com/mdx-js/mdx/blob/master/.remarkrc.js#L19) rule is disabled in `mdx-js/mdx`.

As I know asynchronous rule is not supported by ESLint itself right now, or is there any workaround to support?

Related: #73

**Comment by wooorm** [comment]
Ahh okay, didn’t know ESLint didn’t support that 🤔

**Comment by karlhorky** [comment]
Looks like ESLint is getting parallel processing support: https://github.com/eslint/rfcs/pull/42

(eslint/rfcs#4 is closed now)

**Comment by JounQin** [comment]
Cannot do much before ESLint changes.

**Comment by karlhorky** [comment]
Wow, this is great! Does this mean that the `validate-links` rule will be enabled again for Markdown / MDX?

Is there anywhere where we can follow along with this?

**Comment by JounQin** [comment]
@karlhorky 

Yes! You can try it with latest codesandbox build right now.

https://ci.codesandbox.io/status/mdx-js/eslint-mdx/pr/309/builds/125085

**Comment by JounQin** [comment]
[v1.13.0](https://github.com/mdx-js/eslint-mdx/releases/tag/v1.13.0) has been released!
