### ISSUE TITLE
eslint-plugin-mdx uses dependency cosmiconfig that uses for async, not supported until node 10

### ISSUE THREAD

**Issue by jjoselv** [mdx-js/eslint-mdx#248]
### Subject of the issue

Describe your issue here.

eslint-plugin-mdx uses dependency cosmiconfig that uses `for async`, not supported until node 10: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of
```
/var/lib/jenkins/workspace/#####/node_modules/eslint-plugin-mdx/node_modules/cosmiconfig/dist/Explorer.js:54
    for await (const place of this.config.searchPlaces) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at NativeCompileCache._moduleCompile (/var/lib/jenkins/workspace/#####/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/var/lib/jenkins/workspace/#####/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/var/lib/jenkins/workspace/#####/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/lib/jenkins/workspace/#####/node_modules/eslint-plugin-mdx/node_modules/cosmiconfig/dist/index.js:12:17)
    at Module._compile (/var/lib/jenkins/workspace/#####/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```
### Your environment

*   **OS**: windows
*   **Packages**: eslint-plugin-mdx": "^1.8.2"
*   **Env**: node: v8.11.3, npm 6.1.0

### Steps to reproduce

Fails on linting mdx files: (npm run lint)

### Actual behaviour

Doesn't fail

### Expected behaviour

The package.json for eslint-plugin-mdx is:
´´´
"engines": {
    "node": ">=7.0.0"
  },
´´´

Because of this, it may needed to, either upgrade to >10 or resolve the dependency node requirements for cosmiconfig

**Comment by JounQin** [comment]
Thanks for your point, `cosmiconfig` requires `node>= 10` now, PR welcome to upgrade the `engines` field.

**Comment by jjoselv** [comment]
Created
