### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'start' in undefined

### ISSUE THREAD

**Issue by EthanShoeDev** [mdx-js/eslint-mdx#520]
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"eslint-plugin-mdx": "^3.1.4"

### Link to runnable example

https://codesandbox.io/p/devbox/eslint-plugin-mdx-typeerror-remark-lint-xqwl2v

### Steps to reproduce

Steps to reproduce:

1. Start with [MDX Loader with Next.js](https://codesandbox.io/s/github/mdx-js/.github/tree/main/sandbox-templates/mdx-loader-next) codesandbox from issue template.
2. Install `eslint` and `eslint-mdx`
```bash
npm i -D eslint-plugin-mdx eslint
```
3. Add eslint config file `.eslintrc`. Config pulled [directly from readme](https://github.com/mdx-js/eslint-mdx?tab=readme-ov-file#classic).
```
{
  "extends": ["plugin:mdx/recommended"],
  "settings": {
    "mdx/code-blocks": true,
    "mdx/language-mapper": {}
  }
}
```
4. Install `remark-lint`. [reference](https://github.com/remarkjs/remark-lint?tab=readme-ov-file#example-check-markdown-on-the-api)
```bash
npm install vfile-reporter remark remark-preset-lint-consistent remark-preset-lint-recommended remark-lint-list-item-indent --save-dev
```
5. Setup remark config by adding `remarkConfig` to `package.json`. Config pulled directly [from remark-lint readme](https://github.com/remarkjs/remark-lint?tab=readme-ov-file#example-check-markdown-on-the-cli).
6. Remove the trailing new line from `pages\index.mdx`.
7. Run `npx eslint . --ext mdx` and result is:
```bash
/workspace git:(master) ✗ npx eslint . --ext mdx

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot use 'in' operator to search for 'start' in undefined
Occurred while linting /workspace/pages/index.mdx:1
Rule: "mdx/remark"
    at Program (/workspace/node_modules/eslint-plugin-mdx/lib/rules/remark.js:67:38)
    at ruleErrorHandler (/workspace/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:803:23)
    at /workspace/node_modules/eslint/lib/linter/linter.js:1111:32
```

### Expected behavior

eslint should output:

```bash
/workspace git:(master) ✗ npx eslint . --ext mdx

/workspace/pages/index.mdx
  1:1  warning  Missing newline character at end of file  remark-lint-final-newline

✖ 1 problem (0 errors, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

### Actual behavior

eslint outputs:

```bash
/workspace git:(master) ✗ npx eslint . --ext mdx

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot use 'in' operator to search for 'start' in undefined
Occurred while linting /workspace/pages/index.mdx:1
Rule: "mdx/remark"
    at Program (/workspace/node_modules/eslint-plugin-mdx/lib/rules/remark.js:67:38)
    at ruleErrorHandler (/workspace/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/workspace/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/workspace/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/workspace/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:803:23)
    at /workspace/node_modules/eslint/lib/linter/linter.js:1111:32
```

### Runtime

Node v20

### Package manager

npm v9

### OS

Linux

### Build and bundle tools

Next.js

**Comment by HeavenlyEntity** [comment]
I'm getting this error in the latest version of Next.js 15.3.2. What wound up being the solution to fix this issue?

```shell
./apps/lander/src/app/(marketing)/work/unseal/page.mdx
Error evaluating Node.js code
TypeError: Cannot use 'in' operator to search for 'plugins' in null
    [at addPreset (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:1109:23)]
    [at add (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:1097:11)]
    [at addList (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:1134:11)]
    [at Function.use (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/unified@11.0.5/node_modules/unified/lib/index.js:1074:9)]
    [at createProcessor (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/@mdx-js+mdx@3.1.0_acorn@8.14.1/node_modules/@mdx-js/mdx/lib/core.js:209:6)]
    [at split (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/@mdx-js+mdx@3.1.0_acorn@8.14.1/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:85:37)]
    [at process (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/@mdx-js+mdx@3.1.0_acorn@8.14.1/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:62:31)]
    [at Proxy.loader (file:///Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/@mdx-js+loader@3.1.0_acorn@8.14.1/node_modules/@mdx-js/loader/lib/index.js:89:3)]
    [at /Users/mipi-founder/Documents/GitHub/kingdom-kode-mono/node_modules/.pnpm/@mdx-js+loader@3.1.0_acorn@8.14.1/node_modules/@mdx-js/loader/index.cjs:32:26]
```

**Comment by EthanShoeDev** [comment]
@HeavenlyEntity I believe you are seeing a different issue. The issue in my example was that an eslint rule was reporting an error but it was not including metadata for where the rule violation was occurring within the file.

Your issue looks like something is looking for plugins to exist but it is null instead.

The fix for my issue was to ensure that the rule violation included cursor position in the file before referencing that property. https://github.com/EthanShoeDev/eslint-mdx/commit/f2183fcbdad9aefdc2066ea56d3e8407c2b4fc4f
